### ISSUE TITLE
Some dependent libraries are much unmaintained :(

### ISSUE THREAD

**Issue by justinclift** [RecoLabs/redash-go-sdk#5]
While starting to poke through this Redash Go SDK today, something interesting turned up.  Two of the Go libraries it uses are unmaintained (one is even archived):

* https://github.com/PuerkitoBio/urlesc
  * Archived by the project owner.  It's pretty doubtful that using this is a good idea.
* https://github.com/PuerkitoBio/purell
  * It's not archived (yet), instead it has a message saying it's looking for a maintainer to take it over:
  ```
  LOOKING FOR A MAINTAINER. I don't use purell these days, and as such I don't give it much attention and
  care.  If you use it in your project(s) and would be interested in taking good care of it, please reach
  out.  See https://github.com/PuerkitoBio/purell/issues/33.
  ```

Not a complete blocker, but they should probably be either swapped out for something else, or picked up and carried forward (eg become the maintainer, etc).

**Comment by ShayNehmad-RecoLabs** [comment]
Hi @justinclift, thanks for pointing this out!

We're using Snyk to verify that the dependencies don't pose security risks, and while these deps are outdated, as long as they don't cause security concerns, we won't work too hard to replace them ;) I'll try to link to the Snyk results in the README.

Thanks a lot! Hope the SDK has been useful for you.

**Comment by ShayNehmad-RecoLabs** [comment]
Actually, looks like [snyk badges don't work](https://github.com/snyk/snyk/issues/347), So I won't add it to the README - but it does notify me over email.

Closing as `wontfix` - again, thanks a lot for your feedback @justinclift!
